spring:
  datasource:
    url: jdbc:mysql://localhost:3306/slogans?useSSL=false&allowPublicKeyRetrieval=true
    password: slogan
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true